on:
  push:
    paths:
      - 'DESCRIPTION'
      - 'vignettes/*.Rmd'
jobs:
  job1:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    
    env:
        namespace: ${{ secrets.ANVIL_NAMESPACE }}
        name: ${{ secrets.ANVIL_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Install BiocManager
        run: |
            install.packages('remotes')
            remotes::install_cran("BiocManager")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
            BiocManager::install(c("AnVILPublish", "notedown"))
        shell: Rscript {0}

      - name: Publish to AnVIL
        #env: can I get environment variables for AnVIL name / namespace?
        run: AnVILPublish::as_workspace(path = , namespace = env.namespace, name = env.name, update = TRUE)
        shell: Rscript {0}
