on:
  push:
    paths:
      - 'DESCRIPTION'
      - 'vignettes/*.Rmd'

name: anvilpublish-action

jobs:
  anvilpublish-action:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    
    env:
        namespace: ${{ secrets.ANVIL_NAMESPACE }}
        name: ${{ secrets.ANVIL_NAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install python module notedown
        run: pip install notedown

      - name: Install BiocManager
        run: |
            install.packages('remotes')
            remotes::install_cran("BiocManager")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
            BiocManager::install('AnVILPublish')
        shell: Rscript {0}

      - name: Publish to AnVIL
        #env: can I get environment variables for AnVIL name / namespace?
        run: AnVILPublish::as_workspace(path = getwd(), namespace = ${{ secrets.ANVIL_NAMESPACE }}, name = ${{ secrets.ANVIL_NAME }}, update = TRUE)
        shell: Rscript {0}
