on:
  push:
    paths:
      - 'DESCRIPTION'
      - 'vignettes/*.Rmd'

name: anvilpublish-action

jobs:
  anvilpublish-action:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    
    env:
        namespace: ${{ secrets.ANVIL_NAMESPACE }}
        name: ${{ secrets.ANVIL_NAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3
       
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
 
      - name: Install python module notedown
        run: pip3 install notedown

      - name: Install dependencies
        run: |
            BiocManager::install('AnVILPublish')
        shell: Rscript {0}

      - name: Publish to AnVIL
        run: |
            Sys.getenv()
            AnVILPublish::as_workspace(path = getwd(), namespace = namespace, name = name, update = TRUE)
        shell: Rscript {0}
