on:
  push:
    paths:
      - 'DESCRIPTION'
      - 'vignettes/*.Rmd'

name: anvilpublish-action

jobs:
  anvilpublish-action:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    
    env:
        namespace: ${{ secrets.ANVIL_NAMESPACE }}
        name: ${{ secrets.ANVIL_NAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install BiocManager
        run: |
            install.packages('remotes')
            remotes::install_cran("BiocManager")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
            BiocManager::install(c("AnVILPublish", "notedown"))
        shell: Rscript {0}

      - name: Publish to AnVIL
        #env: can I get environment variables for AnVIL name / namespace?
        run: AnVILPublish::as_workspace(path = ".", namespace = ${{ secrets.ANVIL_NAMESPACE }}, name = ${{ secrets.ANVIL_NAME }}, update = TRUE)
        shell: Rscript {0}
