on:
  push:
    paths:
      - 'DESCRIPTION'
      - 'vignettes/*.Rmd'

name: anvilpublish-action

jobs:
  anvilpublish-action:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    
    env:
        namespace: ${{ secrets.ANVIL_NAMESPACE }}
        name: ${{ secrets.ANVIL_NAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}

    permissions:
        contents: 'read'
        id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
           workload_identity_provider: ${{ secrets.WRKLOAD_ID_PROVIDER }}
           service_account: ${{ secrets.SERVICE_ACCOUNT }}

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: 'gcloud-set-project'
        name: 'gcloud set project'
        run: |-
            gcloud config set project "${{ secrets.ANVIL_NAMESPACE }}"

      - id: 'gcloud-info'
        name: 'gcloud info'
        run: |-
          gcloud info

      # Now you can run gcloud commands authenticated as the impersonated service account.
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud secrets versions access "latest" --secret "my-secret"
 
#      - name: Install python module notedown
#        run: pip3 install notedown

#      - name: Install dependencies
#        run: |
#            BiocManager::install('AnVILPublish')
#        shell: Rscript {0}

#      - name: Publish to AnVIL
#        run: |
#            namespace <- Sys.getenv("namespace")
#            name <- Sys.getenv("name")
#            AnVILPublish::as_workspace(path = getwd(), namespace = namespace, name = name, update = FALSE, create = FALSE)
#        shell: Rscript {0}
