on:
  push:
    paths:
      - 'DESCRIPTION'
      - 'vignettes/*.Rmd'

name: anvilpublish-action

jobs:
  anvilpublish-action:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel
    
    env:
        namespace: ${{ secrets.ANVIL_NAMESPACE }}
        name: ${{ secrets.ANVIL_NAME }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
            workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
       
      - uses: google-github-actions/setup-gcloud@v0
 
      - name: Install python module notedown
        run: pip3 install notedown

      - name: Install dependencies
        run: |
            BiocManager::install('AnVILPublish')
        shell: Rscript {0}

      - name: Publish to AnVIL
        run: |
            Sys.getenv()
            AnVILPublish::as_workspace(path = getwd(), namespace = namespace, name = name, update = TRUE)
        shell: Rscript {0}
